### ISSUE TITLE
create some output from list

### ISSUE THREAD

**Issue by 42sol-eu** [okken/cards#13]
* cards version: 0.1.5
* Python version: 3.6.3
* Operating System: winDO(w)S 10

### Description

create a command that will output the cards to a transfer file (JSON, YAML, Markdown)

### What I Did

this is a feature request ... 😄

**Comment by 42sol-eu** [comment]
this coul be implemented via clicks plugin example (complex example) I do have a working prototype. The export to Yaml and Json is a one liner in python though

**Comment by okken** [comment]
Version 0.1.12 adds --format, which can be used for markdown.

```
$ cards list -f pipe
|   ID | owner   | done   | summary      |
|-----:|:--------|:-------|:-------------|
|    2 | Brian   |        | another task |
```

which produces this in git flavored markdown:

|   ID | owner   | done   | summary      |
|-----:|:--------|:-------|:-------------|
|    2 | Brian   |        | another task |

**Comment by okken** [comment]
Current master (not on pypi yet) has --format=markdown and --format=json working. Let me know what you think.

**Comment by okken** [comment]
Since yaml requires an external dependency, I think I'll leave that out for the time being.

**Comment by okken** [comment]
However, that would be a good use of a plugin/hook system, and we could push the json code to a plugin as an example.

**Comment by okken** [comment]
lots of formats now, marking this as fixed.
