### ISSUE TITLE
update the default issue template

### ISSUE THREAD

**Issue by okken** [okken/cards#16]
Not sure the default template for issues is really helpful... 
Not sure what it should be though either.

Here's the existing template:

<pre>
* cards version: 
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
</pre>

**Comment by 42sol-eu** [comment]
you are right it is targeted as an error entry. to use issues as standard threads for all cases of changes makes it kind of bulky. Github itself uses the same approach.

**Comment by okken** [comment]
closing old issues
