### ISSUE TITLE
ability to add more states 

### ISSUE THREAD

**Issue by 42sol-eu** [okken/cards#22]
* cards version: latest
* Python version: all
* Operating System: all

### Description
replace the boolean column with a state column (string or enum) and give the user a plugin interface to define her own states

e.g. new, active, rejected, done

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by okken** [comment]
remove "via plugin", as it's an implementation detail

**Comment by okken** [comment]
In thinking about this, it's outside the scope of the project. 
The initial intent of the project is really, "stuff we are working on"
