### ISSUE TITLE
ability to add more columns

### ISSUE THREAD

**Issue by 42sol-eu** [okken/cards#23]
* cards version: latest
* Python version: all
* Operating System: all

### Description
give the user a way to add more columns (project and context — gtd calling)
with plugins

I would really like to see how this would be tested

**Comment by okken** [comment]
Changed description from "add more columns via plugins" to "ability to add columns".
The "via plugins" seems like an implementation detail.
Perhaps it's the right way to implement it, but I don't want to limit the possibilities.

**Comment by tutordelphia** [comment]
I would definitely like a priorities column to have a way of sorting the list

**Comment by 42sol-eu** [comment]
I thought about that. I would divide it into card entries and card links. If you think about owners and projects they could eventually become their own objects, priorities or context might be a entry in the card. for the entries it might be easy to put a dictionary in the card class and let the user fill it with data.

**Comment by StevenCHowell** [comment]
>I would definitely like a priorities column to have a way of sorting the list

In addition to priorities, it would be helpful to support due dates and tags.  These might not necessarily have to be separate columns.  Looking at the [markdo project](https://github.com/benjaminoakes/markdo), it seems they use decorators for this.

Sorting on priority or due-date would definitely be valuable (perhaps this deserves a separate issue?).

**Comment by okken** [comment]
'priority' has been added. Will hold off others for now
