### ISSUE TITLE
add subtasks

### ISSUE THREAD

**Issue by adamzev** [okken/cards#27]
I'd like the ability to add subtasks with a command like: cards add "summary" 5
That would add "summary" as a subtask to task 5. A flag could determine whether subtasks are displayed on the main list and there would need to be a way to display the subtasks.

**Comment by 42sol-eu** [comment]
that should be easily implemented, would need a new element in the Card class for a parent task id. 
No entry would set it to a parent task.

Interesting is still the question how this would change the click interface. e.g Filtering

**Comment by okken** [comment]
I think this is outside the scope of the current project.
