### ISSUE TITLE
Cannot `pip install -e .` because of missing `setup.py` file

### ISSUE THREAD

**Issue by jradek** [okken/cards#48]
* cards version: ?
* Python version: 3.8
* Operating System: MacOS 10.15.16

### Description / What I Did

I followed the `Get Started` [section](https://github.com/okken/cards/blob/master/docs/contributing.md#get-started) in the _Contributing_ document.

However, the step

```console
pip install -e .
```
fails with: `ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /Users/xxx/cards
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)`

**Comment by okken** [comment]
Sorry about that. The project is currently getting a large make-over. Hoping to get some new content pushed up soon.
Instead of `pip install -e .`, try 
```
pip install flit
flit install --pth-file
```

**Comment by jradek** [comment]
Thanks for the fast response!
The posted solution solves the problem.
I updated the guide accordingly and created a pull request.
